app/internal/ibus: don't build under GOOS=js
github.com/godbus/dbus/v5 doesn't build under GOOS=js:

  # github.com/godbus/dbus/v5
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:44:19: undefined: syscall.MSG_CTRUNC
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:62:9: cannot use t (variable of type *unixTransport) as transport value in return statement: *unixTransport does not implement transport (missing method SendNullByte)
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:79:10: cannot use t (variable of type *unixTransport) as transport value in return statement: *unixTransport does not implement transport (missing method SendNullByte)
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:85:10: cannot use t (variable of type *unixTransport) as transport value in return statement: *unixTransport does not implement transport (missing method SendNullByte)
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:198:24: undefined: syscall.ParseSocketControlMessage
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:205:23: undefined: syscall.ParseUnixRights
  ../go/pkg/mod/github.com/godbus/dbus/v5@v5.2.2/transport_unix.go:273:18: undefined: syscall.UnixRights

Signed-off-by: Elias Naur <mail@eliasnaur.com>